---
driver:
  name: vagrant

provisioner:
  name: dummy

platforms:
  - name: qwerty1979/redis64

verifier:
  name: inspec

suites:
  - name: default
    verifier:
      inspec_tests:
        - redis_test.rb
